### ISSUE TITLE
`--follow-exec` causes segfault on GitHub Actions

### ISSUE THREAD

**Issue by jwodder** [xd009642/tarpaulin#1046]
I'm trying to set up & configure tarpaulin under GitHub Actions with Codecov.  At first, the only problem was that my binary crate wasn't marked as covered despite being tested by an integration test; then, I found the `--follow-exec` option.  Unfortunately, if I pass this option to tarpaulin (using v0.20.1 on Rust stable, beta, & nightly), it segfaults when running the binary crate tests.

Here is my GitHub Actions workflow in which I run tarpaulin:

```yaml
name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure Git identity
        # Needed for a couple tests
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'ghactions@nil.nil'

      - name: Install Rust
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
          cargo install cargo-tarpaulin

      - name: Test with coverage
        run: cargo tarpaulin --out Xml --exclude-files "tests/*" --follow-exec

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
```

and here is a link to the segfaulting runs: https://github.com/jwodder/ghrepo-rust/actions/runs/2632179108.
