### ISSUE TITLE
GitHub action actions-rs/tarpaulin fails when version is set to 'latest', which is the default

### ISSUE THREAD

**Issue by tokcum** [xd009642/tarpaulin#1256]
Hi,

I'm using actions-rs/tarpaulin in my GitHub action workflows. The workflow started to fail a while ago and I was wondering why.

The error is (see [details](https://github.com/polarlabs/kodiak-taxonomy/actions/runs/4583491742/jobs/8094367922)):

```
Error: Couldn't find a release tarball containing binaries for latest
```

Today I found the time to investigate this. My assumption was that this has something to do with the artifacts released by tarpaulin.

This is the relevant job from my workflow.

```
- name: check-coverage
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: latest
          args: --ignore-tests --out Xml --fail-under 100
```

So, first I changed the from 'latest' to '0.25.1' which yield the same error. Then I switched to '0.22.0' and the error was gone.

I reviewed the artifacts released at GitHub and realized that 0.22.0 was the last version releasing a `cargo-tarpaulin-0.22.0-travis.tar.gz`. Another difference is that 0.22.0 was the last version which released only one "binary".

I also checked the repo providing action-rs/tarpaulin but there were no changes for a long time.

I hope this helps in understanding and reproducing the issue. Thanks for your support.
