### ISSUE TITLE
tarpaulin_include needs adaptation for the new rust cfg checking lint

### ISSUE THREAD

**Issue by HadrienG2** [xd009642/tarpaulin#1554]
A project that uses `#[cfg(not(tarpaulin_include))]` cfg as directed in the README will emit a warning on current nightlies due to the [new `unexpected_cfgs` lint of rustc](https://blog.rust-lang.org/2024/05/06/check-cfg.html).

It would be a good idea to document this fact and suggest mitigation options like adding `cfg(tarpaulin_include)` to the `[lints.rust.unexpected_cfgs]` of `Cargo.toml`.

This is how I did it in my project:

```toml
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(tarpaulin_include)"] }
```

Longer term, it would probably be a good idea to investigate if an alternative with better ergonomics than checking a cfg that does not exist in the eyes of rustc can be provided.
