### ISSUE TITLE
How to setup Coveralls using GitHub Actions for a Rust project using tarpaulin

### ISSUE THREAD

**Issue by szabgab** [xd009642/tarpaulin#1614]
Suggestion for the README:

In order to setup [Coveralls](https://coveralls.io/) using GitHub Action follow these steps:

* Login to [Coveralls](https://coveralls.io/) with your GitHub credentials.
* Find your repo on on [Coveralls new page](https://coveralls.io/repos/new) and enable it.
* In your GitHub action configuration run tarpaulin with the `-o Lcov` flag. e.g. `cargo tarpaulin --ignore-tests -o Lcov`.
* Add the following section to your GitHub workflow yaml file after the step that runs tarpaulin:

```
 - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        file: lcov.info
```

* Enjoy

For an example check out the [meet-os](https://github.com/szabgab/meet-os.rs/) project and its [coveralls report](https://coveralls.io/github/szabgab/meet-os.rs)
