### ISSUE TITLE
Branch not reported correctly on coveralls.io

### ISSUE THREAD

**Issue by bitfl0wer** [xd009642/tarpaulin#1697]
I am using tarpaulin with coveralls.io. coveralls supports viewing coverage on branches. However, coverage data generated from runs on branches does not get recognized correctly:

![Screenshot of a CI (Continuous Integration) dashboard titled “RECENT BUILDS.” The table displays eight rows, labeled #8 through #1, with column headers for “BUILDS,” “BRANCH,” “COMMIT MESSAGE,” “TYPE,” “RAN,” “COMMITTER,” “VIA,” and “COVERAGE.” Each row shows a build number, the corresponding Git branch (e.g., “main”), a short commit message (including one reading “use LLM and no-dead-code as recommended by tarpaulin for linux” and another reading “[no commit message]”), the build trigger type (“push”), the date and time the build ran, the committer (displayed as “bottower”), how it was triggered (“via bottower”), and a coverage percentage in the last column (ranging around the 66–76% range in red and orange bars). Notably, the coverage values appear inconsistent for branch builds, suggesting that coverage runs on non-main branches are not being recognized correctly (some entries are missing or remain at an unexpected value), whereas main branch builds do show an updated coverage percentage.](https://github.com/user-attachments/assets/a36c58bc-92da-4aad-b978-61d1ebcb8f46)

## GitHub actions workflow

```yml
runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          prefix-key: "coverage"
      - name: Build, Publish Coverage
        run: |
          if [ -n "${{ secrets.COVERALLS_REPO_TOKEN }}" ]; then
              curl -L --proto '=https' --tlsv1.3 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
              cargo binstall --no-confirm cargo-tarpaulin --force
              cargo tarpaulin --no-dead-code --engine llvm --all-features --tests --verbose --skip-clean --coveralls ${{ secrets.COVERALLS_REPO_TOKEN }} --timeout 120
          else
              echo "Code Coverage step is skipped on PRs from forks."
          fi
```

## Expected outcome

In this scenario, I'd expect the branch name and commit message data to be submitted to coveralls correctly. Am I doing something wrong with my command invocation?
