### ISSUE TITLE
specifying include filter in tarpaulin.toml

### ISSUE THREAD

**Issue by bradwood** [xd009642/tarpaulin#467]
Hi,

This is probably a newbie/stupid question, but how do I specific a specific set of tests to _include_ in a tarpaulin invocation? I want to merge the coverage from 2 runs using the toml file, and include/exclude subsets by substring. For excluding `--skip` or `--exclude-*` will work, but I can't figure out how to _include_ using the toml file. 

A normal `cargo test` invocation just takes a `<TESTNAME>` which does the substring match for inclusions - but I don't know how to represent this in the toml.

Cheers

**Comment by bradwood** [comment]
Figured it out.

```toml
[CONFIG_ONLY]
locked = true
ignore-tests = true
args = ["config_unit_tests", "--test-threads=1"]

[EVERYTHING_ELSE]
locked = true
ignore-tests = true
args = ["--skip", "config_unit_tests", "--test-threads=1"]

[report]
output-dir = "tarp"
out = ["Html"]
```
