### ISSUE TITLE
Unrecognized option run-types

### ISSUE THREAD

**Issue by ALiuGuanyan** [xd009642/tarpaulin#597]
I follow the [#13](https://github.com/xd009642/tarpaulin/issues/13) and try to get the coverage of doctests in Github Action.

Here is my ci.yml:
```yml
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
    - 'COPYRIGHT'
    - 'LICENSE-*'
    - '**.md'
    - '**.txt'
  pull_request:
    paths-ignore:
    - 'COPYRIGHT'
    - 'LICENSE-*'
    - '**.md'
    - '**.txt'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Run cargo vendor
        uses: actions-rs/cargo@v1
        with:
          command: vendor

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '-- --run-types Doctests Tests'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
```

Here is the error:
```
...
error: Unrecognized option: 'run-types'
Error: Error: "Test failed during run"
Error: The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 1
```
