### ISSUE TITLE
Cannot use features + workspace from cargo tarpaulin (works from cargo test)

### ISSUE THREAD

**Issue by djeedai** [xd009642/tarpaulin#631]
Using tarpaulin 0.16.0 due to a bug in later version(s).

I am trying to invoke tarpaulin to build a **single** unified Lcov report (because coveralls.io only supports 1 report per build per GitHub repo) of a workspace with 3 different runs:
- library A with feature set X
- library A with feature set Y
- binary B

Previously the project was configured without workspace (there was no binary B) and everything worked fine via a `tarpaulin.toml` config:

```toml
[X]
no-default-features = true
features = "default"

[Y]
no-default-features = true
features = ""

[report]
out = ["Lcov"]
```

Here feature set X is "default", and feature set Y is no feature at all. This produced a single Lcov report as expected, which merged the results of both runs and gave a global coverage for the project. All good.

Now converting the GitHub repository and adding workspace, and things are falling over. First there is a limitation (from cargo I think) which prevents using `--features` from the root of the (virtual) workspace. This can be worked around in a single build or test by using `--manifest-path`, _e.g._ manually:

```
cd <PROJECT_ROOT>
cargo build --manifest-path lib/Cargo.toml --no-default-features --features "default"
cargo build --manifest-path lib/Cargo.toml --no-default-features --features ""
cargo build --manifest-path bin/Cargo.toml
```

This works with `cargo test` too and will do what is expected : build/test the specific package with the specific feature set, and nothing else.

However when used with tarpaulin, it seems this doesn't work. I tried to specify `manifest-path = "lib"` in each coverage variant:

```toml
[X]
manifest-path = "lib/Cargo.toml"
no-default-features = true
features = "default"

[Y]
manifest-path = "lib/Cargo.toml"
no-default-features = true
features = ""

[B]
manifest-path = "bin/Cargo.toml"
```

but that doesn't work, and cargo still complains that `--features` cannot be used, which is the error one would get manually if **not** specifying `--manifest-path`:

```
error: --features is not allowed in the root of a virtual workspace
note: while this was previously accepted, it didn't actually do anything
```

It seems that `cargo tarpaulin` is not invoking the build/test the same way a direct command-line invoke of `cargo build` or `cargo test` does. I see no way to work around this, and this is blocking me from using a workspace and adding a binary crate to my repository.
