### ISSUE TITLE
Coverage caching does not play well with shared target directory

### ISSUE THREAD

**Issue by paulvt** [xd009642/tarpaulin#710]
**Describe the bug**

I use a shared target directory for Cargo. However, Tarpaulin writes its coverage (cache) to `coverage.json` in the root of the target directory, replacing the result of the previous run, even it is of another project. As a result Tarpaulin gets confused if you run `cargo tarpaulin` first for project A and then in B, as the second run shows its coverage delta calculation relative to the previous run for project A, leading to confusing output.

**To Reproduce**
```
$ export CARGO_TARGET_DIR=/tmp/cargo-target
$ cd projectA
$ cargo tarpaulin
...
88.04% coverage, 1995/2266 lines covered, +88.04% change in coverage
$ cd ../projectB
$ cargo tarpaulin
...
29.12% coverage, 852/2926 lines covered, -58.92235000564075% change in coverage
$ cd ../projectA
..
88.04% coverage, 1995/2266 lines covered, +58.92235000564075% change in coverage
```

**Expected behavior**

I expected the results to be relative to project I run Tarpaulin for.

It might be that this bug report just needs to be transformed into a feature request for safe shared target directory support?

**Comment by xd009642** [comment]
hmm yeah I could add the project name into the folder name. I don't suppose you use criterion and know how they handle it?

**Comment by paulvt** [comment]
It sees Cargo itself uses things like `crate-<some ID>` here and there, but it seems per crate and not per project and I don't know how this is generated and when?

**Comment by paulvt** [comment]
On a side note: I actually use a separate shared target directory for Tarpaulin itself during CI when using target dir caching. If one does not do this, a `cargo build` followed by `cargo tarpaulin` will do two builds, and leave the (cached) target directory in a state that `cargo build` will rebuild and then Tarpaulin also will rebuild again on a following run. Thus negating the purpose of caching the target directory for CI. It might be worthwhile make a remark about this in the README (once this issue is fixed I guess)?

E.g., I use with GitLab CI:

```yaml
cache:
  paths:
    - ...
    - target/
...

build_and_test:
  script:
    - rustc --version && cargo --version
    ...
    - cargo build --all-features --all-targets
    - cargo tarpaulin --all-features --ignore-tests --target-dir=$CARGO_TARGET_DIR/tarpaulin
```

However, doing this is not only nice for CI but also while developing :wink:, i.e. have `cargo build` not interfere with `cargo tarpaulin` runs and being incremental again.
