### ISSUE TITLE
Doctests not running in workspace

### ISSUE THREAD

**Issue by jeremylt** [xd009642/tarpaulin#747]
**Describe the bug**
We saw a decrease in reported coverage from the `actions-rs/tarpaulin@v0.1` GitHub action. Investigating, the action stopped running our Doctests after the release of `0.18.0-alpha2`.

**To Reproduce**
Action result with `0.16.0`: https://github.com/CEED/libCEED/runs/2460132339?check_suite_focus=true
Action result with `0.18.0-alpha1`: https://github.com/CEED/libCEED/runs/2356977685?check_suite_focus=true
Action result with `0.18.0-alpha2`: https://github.com/CEED/libCEED/runs/2367015830?check_suite_focus=true

Current yml:
<details>

```yml
name: Rust

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        compiler: [clang]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Environment setup
      uses: actions/checkout@v2
    - name: Rust setup
      uses: actions-rs/toolchain@v1
      with:
        # Note: nightly required for coverage of Doctests with tarpaulin
        toolchain: nightly
        override: true
    - name: Rust test with coverage
      uses: actions-rs/tarpaulin@v0.1
      env:
        CC: ${{ matrix.compiler }}
        FC: gfortran-9
      with:
        version: '0.16.0'
        args: '--run-types Doctests Tests --exclude-files backends/* gallery/* include/* interface/*'
    - name: Codecov upload
      uses: codecov/codecov-action@v1.0.2
      with:
        directory: target/tarpaulin
        token: ${{secrets.CODECOV_TOKEN}}

  style:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        compiler: [clang]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Environment setup
      uses: actions/checkout@v2
    - name: Rust setup
      uses: actions-rs/toolchain@v1
      with:
        # Note: rustfmt not always included in nightly, will attempt to downgrade until rustfmt found
        toolchain: nightly
        components: rustfmt
    - name: Rust style
      run: |
        cargo +nightly fmt --version
        cargo +nightly fmt -- --check
```
</details>

We use a workspace to simplify management of our crate and two examples. I have not verified yet, but I am wondering if the PRs to update how rustflags are managed aren't working as intended for workspaces.

I have a current workaround by pinning to `0.16.0` in the `actions-rs/tarpaulin@v0.1` action. I haven't dug further yet because I have a functioning workaround. Please let me know if I'm missing something dumb!

**Expected behaviour**
The expected behaviour is for Doctests to run when calling `cargo tarpaulin --run-types Doctests Tests` in the top level of a workspace in `0.18.0-alpha2`, as seen with `0.18.0-alpha1` and earlier.
