### ISSUE TITLE
`skip-clean` is not being picked up from tarpaulin.toml

### ISSUE THREAD

**Issue by hiradp** [xd009642/tarpaulin#922]
**Describe the bug**

Adding `skip-clean` to the config yaml has no impact. One still needs to supply it with the command line, so I guess not really a high priority. 

**To Reproduce**

A simple rust project with the following as in the root `tarpaulin.toml`:

```yaml
[all]
exclude-files=[
    "bench/*",
    "build.rs",
    "src/lib.rs",
    "test/**/*",
    "mod.rs"
]
fail-under=70
no-fail-fast=true
skip-clean=true
```

With a simple GitHub actions workflow:

```yaml
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.18.5'
          args: '--output-dir ./dev/coverage'
          out-type: Html

      - name: Upload code coverage results as artifacts
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: dev/coverage/tarpaulin-report.html
```

The `fail-under` is picking up, so I know the config is being recognized. This will still clean before. You'll need to pass `--skip-clean` to the `jobs.coverage.step.[1].with.args` in the GitHub actions yaml for it to not clean.

**Expected behavior**
I expect that
