### ISSUE TITLE
`skip-clean` and `force-clean` config options not working

### ISSUE THREAD

**Issue by PyroTechniac** [xd009642/tarpaulin#963]
**Describe the bug**
`cargo tarpaulin` doesn't respect the `skip-clean` and `force-clean` config options

Secondary bug: when calling `cargo tarpaulin --skip-clean --force-clean` a warning is thrown up about option incompatibility, but if both `force-clean = true` and `skip-clean = true` are set in a config file, no warning is emitted.

**To Reproduce**
```toml
[all-features-coverage]
workspace = true
all-features = true
ignore-tests = true
skip-clean = true
force-clean = false

[report]
out = ["Html", "Xml"]
```

then call `cargo tarpaulin` twice in a row, it should clean the project each time.

**Expected behavior**
No cleaning of the project should occur.
