### ISSUE TITLE
[QUESTION] How to run code coverage on excluded workspace files

### ISSUE THREAD

**Issue by dutterbutter** [xd009642/tarpaulin#983]
# Overview

I have some directories that I have intentional excluded from my workspace but I still want to account for the code coverage. Is there an option to do so? I reviewed the command line arguments with no luck. In the example below I would like to run code coverage for `member3` and `member4`. Do I have to run the coverage separately? If so, how? 

**Cargo.toml**
```
[workspace]

members = [
    "member1", 
    "member2", 
]

exclude = ["member3", "member4"]
```

Thanks in advance. 🙏🏻

**Comment by xd009642** [comment]
Genuinely sorry I missed this a lot of issues in 2022 and some things just fell by the wayside. 

You may be able to solve it with `--packages member3 member4`  otherwise I'd look at the config file section of  the readme and add a tarpaulin.toml probably something like:

```toml
[main-workspace]
workspace = true

[member-3-coverage]
root = "member3"

[member-4-coverage]
root = "member4"

[report]
# Any output formats you want
```

Tarpaulin will run itself for each section one after the other. Merge the results and then report based on report section. Let me know if you need anymore help (and I'll respond much faster)
